# Gradle設定
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# https://fabricmc.net/develop で確認
minecraft_version=1.19.4
yarn_mappings=1.19.4+build.2
loader_version=0.14.21

# Mod Properties
mod_version=2.2
maven_group=com.scserver.serverscoreboard
archives_base_name=mysb-1.19.4

# Dependencies
fabric_version=0.87.0+1.19.4
