# Gradle設定
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# https://fabricmc.net/develop で確認
minecraft_version=1.19.2
yarn_mappings=1.19.2+build.28
loader_version=0.19.1

# Mod Properties
mod_version=2.3
maven_group=com.astralsmp.mysb
archives_base_name=mysb-1.19.2

# Dependencies
fabric_version=0.77.0+1.19.2
