# Gradle設定
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
# https://fabricmc.net/develop で確認
minecraft_version=1.20
yarn_mappings=1.20+build.1
loader_version=0.19.1

# Mod Properties
mod_version=2.3
maven_group=com.astralsmp.mysb
archives_base_name=mysb-1.20

# Dependencies
fabric_version=0.83.0+1.20
